# Generated by Django 5.0.7 on 2025-08-06 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_check_in',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the user checked in.'),
        ),
    ]
