# Generated by Django 5.0.7 on 2025-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_in_interval_months',
            field=models.PositiveIntegerField(default=6, help_text='Number of months after which user should check in'),
        ),
        migrations.AddField(
            model_name='user',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=10, help_text='Days after notification before triggering delivery'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the inactivity notification was sent', null=True),
        ),
    ]
